services:
    server:
        container_name: signalize
        build: .
        working_dir: /usr/share/nginx/html
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 3000:80
            # Http server for tests
            - 4000:4000
            # Playwright Report
            - 9323:9323
        environment:
            DEV: true
        tty: true
