version: '3'
services:
    server:
        container_name: signalize
        build: .
        working_dir: /var/www
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 3000:80
            # Http server for tests
            - 4000:4000
            # Vite Dev Server
            - 5173:5173
            # Vite Preview
            - 4173:4173
            # Playwright Report
            - 9323:9323
        tty: true
