version: '3'
services:
    server:
        container_name: islands
        build: .
        working_dir: /var/www
        volumes:
            - ./.:/var/www:delegated
        ports:
            # Http server for tests
            - 3000:3000
            # Vite Dev Server
            - 5173:5173
            # Vite Preview
            - 4173:4173
            # Playwright Report
            - 9323:9323
        tty: true
