version: '3'
services:
    server:
        container_name: inslands
        build: .
        working_dir: /var/www
        volumes:
            - ./.:/var/www:delegated
        ports:
            - 3000:3000
        tty: true
